import Gdk from 'gi://Gdk';
import GLib from 'gi://GLib';
import Gtk from 'gi://Gtk';
import Gio from 'gi://Gio';
import { ExtensionPreferences, gettext as _ } from 'resource:///org/gnome/Shell/Extensions/js/extensions/prefs.js';

// Tall enough to show every setting and the build line without scrolling (default is 640x576).
const WINDOW_WIDTH = 640;
const WINDOW_HEIGHT = 680;

/**
 * Reads the build string generated by the Makefile.
 *
 * @param {string} extensionDir - The absolute path to the extension directory.
 * @returns {string} The build string, or a placeholder when running from an unbuilt tree.
 */
function readBuildInfo(extensionDir) {
    try {
        const [, contents] = GLib.file_get_contents(GLib.build_filenamev([extensionDir, 'build-info.txt']));
        return new TextDecoder().decode(contents).trim();
    } catch (e) {
        return _('Build unknown');
    }
}

/**
 * Preferences window implementation for the Grid Workspace extension.
 * Extends ExtensionPreferences and builds the preferences UI using a Gtk.Builder file.
 */
export default class GridWorkspacePreferences extends ExtensionPreferences {
    /**
     * Fills the preferences window with the UI loaded from the settings UI file and binds 
     * the widget events to the corresponding settings.
     *
     * @param {Gtk.Window} window - The preferences window to populate.
     */
    fillPreferencesWindow(window) {
        const uiFile = GLib.build_filenamev([this.path, 'settings.ui']);

        let builder;
        try {
            builder = Gtk.Builder.new_from_file(uiFile);
        } catch (e) {
            console.error('Error creating Gtk.Builder: ' + e);
            return;
        }
        let mainWidget = builder.get_object('main_widget');
        if (!mainWidget) {
            console.error('Error: Could not find main_widget in the UI file');
            return;
        }
        window.add(mainWidget);
        window.set_default_size(WINDOW_WIDTH, WINDOW_HEIGHT);

        // Get settings from the extension. Keep a reference on the window so it lives as long as
        // the bindings, and disconnect our handlers when the window closes.
        const settings = this.getSettings();
        window._settings = settings;
        const handlerIds = [];
        window.connect('close-request', () => {
            handlerIds.forEach(id => settings.disconnect(id));
            handlerIds.length = 0;
            return false;
        });

        // Bind cell shape dropdown.
        const cellShapeDropdown = builder.get_object('cell_shape_dropdown');
        const updateCellShape = () => {
            const shape = settings.get_string('cell-shape');
            cellShapeDropdown.selected = shape === 'circle' ? 0 : 1;
        };
        updateCellShape();
        cellShapeDropdown.connect('notify::selected', () => {
            const shape = cellShapeDropdown.selected === 0 ? 'circle' : 'square';
            settings.set_string('cell-shape', shape);
        });
        handlerIds.push(settings.connect('changed::cell-shape', () => {
            updateCellShape();
        }));

        // Bind cell size scale control.
        const cellSizeScale = builder.get_object('cell_size_scale');
        settings.bind(
            'cell-size',
            cellSizeScale.get_adjustment(),
            'value',
            Gio.SettingsBindFlags.DEFAULT
        );

        // Bind theme settings: inactive and active fill colors.
        handlerIds.push(this._bindColorButton(builder, settings, 'inactive-fill', 'inactive_fill_button'));
        handlerIds.push(this._bindColorButton(builder, settings, 'active-fill', 'active_fill_button'));

        // Bind apps outline color setting.
        handlerIds.push(this._bindColorButton(builder, settings, 'apps-outline-color', 'outline_color_button'));

        // Bind apps outline thickness setting.
        const outlineScale = builder.get_object('outline_thickness_scale');
        settings.bind(
            'apps-outline-thickness',
            outlineScale.get_adjustment(),
            'value',
            Gio.SettingsBindFlags.DEFAULT
        );

        // Bind switch for outline-active setting.
        this._bindSwitch(builder, settings, 'outline-active', 'outline_active_switch');

        // Bind switch for debug-logging setting.
        this._bindSwitch(builder, settings, 'debug-logging', 'debug_logging_switch');

        // Show the build (written by `make install` / `make bundle`).
        builder.get_object('build_label').label = readBuildInfo(this.path);

        // Reset button functionality: reset all settings.
        const resetButton = builder.get_object('reset_button');
        resetButton.connect('clicked', () => {
            settings.reset('cell-shape');
            settings.reset('cell-size');
            settings.reset('inactive-fill');
            settings.reset('active-fill');
            settings.reset('apps-outline-color');
            settings.reset('apps-outline-thickness');
            settings.reset('outline-active');
            settings.reset('debug-logging');
        });
    }

    /**
     * Binds a GSettings key to a switch widget.
     *
     * @param {Gtk.Builder} builder - The Gtk.Builder instance.
     * @param {Gio.Settings} settings - The settings object.
     * @param {string} key - The settings key to bind.
     * @param {string} switchId - The ID of the Gtk switch in the UI.
     *
     * @private
     */
    _bindSwitch(builder, settings, key, switchId) {
        settings.bind(
            key,
            builder.get_object(switchId),
            'active',
            Gio.SettingsBindFlags.DEFAULT
        );
    }

    /**
     * Binds a GSettings key to a Gtk.ColorDialogButton.
     * Initializes the button's color and keeps the button and the setting in sync both ways.
     *
     * @param {Gtk.Builder} builder - The Gtk.Builder instance.
     * @param {Gio.Settings} settings - The settings object.
     * @param {string} key - The settings key to bind.
     * @param {string} buttonId - The ID of the Gtk.ColorDialogButton in the UI.
     * @returns {number} The settings handler ID, to disconnect when the window closes.
     *
     * @private
     */
    _bindColorButton(builder, settings, key, buttonId) {
        const button = builder.get_object(buttonId);
        const settingRgba = () => {
            const rgba = new Gdk.RGBA();
            rgba.parse(settings.get_string(key));
            return rgba;
        };

        // Set initial color.
        button.set_rgba(settingRgba());

        // Update settings when the button's color changes. Skip no-op writes so syncing the
        // button from the setting doesn't write the value straight back.
        button.connect('notify::rgba', () => {
            const rgba = button.get_rgba();
            if (!rgba.equal(settingRgba())) {
                settings.set_string(key, rgba.to_string());
            }
        });

        // Update the button color if settings change externally.
        return settings.connect(`changed::${key}`, () => {
            const rgba = settingRgba();
            if (!rgba.equal(button.get_rgba())) {
                button.set_rgba(rgba);
            }
        });
    }
}
